import {useEffect,useState} from 'react'
import toast from 'react-hot-toast'
import {supabase} from '../lib/supabase'
const labels:Record<string,string>={requested:'Başvurunuz alındı',approved:'İade / iptal talebi onaylandı',rejected:'Başvuru değerlendirildi',refunded:'Banka iadesi kaydedildi',cancelled:'Ödenmemiş sipariş iptal edildi'}
export default function OrderReturn({orderId,admin=false}:{orderId:string;admin?:boolean}){
 const [record,setRecord]=useState<{status:string;reason:string;decision_note?:string;stock_returned?:boolean}|null>(null)
 const [reason,setReason]=useState(''),[bank,setBank]=useState(''),[restock,setRestock]=useState(false),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false)
 async function load(){const {data,error}=await supabase.from('order_return_requests').select('status,reason,decision_note,stock_returned').eq('order_id',orderId).maybeSingle();setFailed(Boolean(error));setRecord(data)}
 useEffect(()=>{void load()},[orderId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function act(action?:string){if(busy)return;setBusy(true);try{const {error}=await supabase.rpc(admin?'decide_order_return':'request_order_return',admin?{p_order_id:orderId,p_action:action,p_note:reason,p_bank_reference:bank||null,p_restock:restock}:{p_order_id:orderId,p_reason:reason});if(error)throw error;await load();setReason('');toast.success('Başvuru işlemi kaydedildi.')}catch{toast.error('İşlem tamamlanamadı. Açıklamayı ve sipariş koşullarını kontrol edin.')}finally{setBusy(false)}}
 if(failed)return <p role="alert" className="text-sm text-red-700">İade başvurusu bilgisi alınamadı.<button onClick={()=>void load()} className="ml-2 min-h-11 underline">Yeniden dene</button></p>
 if(admin&&!record)return null
 return <details className="mt-3 min-w-0 rounded border border-brand-line p-3"><summary className="min-h-11 cursor-pointer font-semibold">{record?labels[record.status]:'İade / iptal başvurusu'}</summary>
 {record&&<div className="space-y-2 break-words text-sm"><p>{record.reason}</p>{record.decision_note&&<p>{record.decision_note}</p>}{record.status==='refunded'&&<p>Gerçek banka işlemi yönetici tarafından kaydedildi. Stok geri girişi: {record.stock_returned?'yapıldı':'yapılmadı'}.</p>}</div>}
 {(!record||admin&&['requested','approved'].includes(record.status))&&<div className="mt-3 space-y-3"><label className="block text-sm">{admin?'Karar açıklaması':'Siparişinizle ilgili talebiniz'}<textarea minLength={10} maxLength={2000} rows={3} className="shop-input mt-1 w-full" value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label>
 {admin&&record?.status==='approved'&&<><label className="block text-sm">Gerçek banka iadesinin işlem / dekont referansı<input className="shop-input mt-1 w-full" value={bank} onChange={e=>setBank(e.target.value)} disabled={busy}/></label><label className="flex min-h-11 items-start gap-2 text-sm"><input type="checkbox" checked={restock} onChange={e=>setRestock(e.target.checked)} disabled={busy}/>Siparişin tüm ürünleri fiziksel olarak geri alındı ve tekrar satılabilir; stoğa bir kez geri girsin.</label><p className="text-sm text-brand-muted">Bu işlem banka transferi yapmaz. Havale iadesini bankada tamamladıktan sonra kaydedin. Kart ödemesi sağlayıcı üzerinden ayrıca yürütülür.</p></>}
 <div className="flex flex-wrap gap-2">{admin?<>{record?.status==='requested'&&<><button disabled={busy||reason.trim().length<10} onClick={()=>void act('approve')} className="shop-btn-secondary">Talebi onayla</button><button disabled={busy||reason.trim().length<10} onClick={()=>void act('cancel')} className="shop-btn-secondary">Ödenmemiş havaleyi iptal et</button></>}<button disabled={busy||reason.trim().length<10} onClick={()=>void act('reject')} className="shop-btn-secondary">Talebi gerekçesiyle reddet</button>{record?.status==='approved'&&<button disabled={busy||reason.trim().length<10||bank.trim().length<5} onClick={()=>{if(confirm('Banka iadesi gerçekten tamamlandı mı?'))void act('refund')}} className="shop-btn-primary">Tam banka iadesini kaydet</button>}</>:<button disabled={busy||reason.trim().length<10} onClick={()=>void act()} className="shop-btn-secondary">{busy?'Gönderiliyor…':'Başvuruyu gönder'}</button>}</div></div>}</details>
}
